/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exercicios;

/**
 *
 * @author Aluno
 */
public class EX01 extends javax.swing.JFrame {

    /**
     * Creates new form EX02
     */
    public EX01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calculate_button = new javax.swing.JButton();
        fahrenheit_label = new javax.swing.JLabel();
        celsius_label = new javax.swing.JLabel();
        fahrenheit_field = new javax.swing.JTextField();
        celsius_field = new javax.swing.JTextField();
        tittle_label = new javax.swing.JLabel();
        resultado_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        calculate_button.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        calculate_button.setText("Calcular");
        calculate_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculate_buttonActionPerformed(evt);
            }
        });

        fahrenheit_label.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        fahrenheit_label.setText("Temperatura em graus Fahrenheit");

        celsius_label.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        celsius_label.setText("Temperatura em graus Celsius");
        celsius_label.setMaximumSize(new java.awt.Dimension(163, 15));
        celsius_label.setMinimumSize(new java.awt.Dimension(163, 15));

        fahrenheit_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fahrenheit_fieldActionPerformed(evt);
            }
        });

        celsius_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celsius_fieldActionPerformed(evt);
            }
        });

        tittle_label.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tittle_label.setText("Conversor de graus Celsius e Fahrenheit");

        resultado_label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(fahrenheit_label, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(celsius_label, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tittle_label, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(resultado_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(calculate_button)))
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(fahrenheit_field, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(celsius_field, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tittle_label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(celsius_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fahrenheit_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(celsius_field, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fahrenheit_field, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(calculate_button, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(resultado_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculate_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculate_buttonActionPerformed
        calcular();
    }//GEN-LAST:event_calculate_buttonActionPerformed

    private void fahrenheit_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fahrenheit_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fahrenheit_fieldActionPerformed

    private void celsius_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celsius_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celsius_fieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EX01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EX01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EX01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EX01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EX01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculate_button;
    private javax.swing.JTextField celsius_field;
    private javax.swing.JLabel celsius_label;
    private javax.swing.JTextField fahrenheit_field;
    private javax.swing.JLabel fahrenheit_label;
    private javax.swing.JLabel resultado_label;
    private javax.swing.JLabel tittle_label;
    // End of variables declaration//GEN-END:variables
    
    private void calcular(){
                
        int check_celsius = celsius_field.getText().length();
        int check_fahrenheit = fahrenheit_field.getText().length();
        
        if (check_celsius != 0 && check_fahrenheit == 0){
            Double celsius = Double.parseDouble(celsius_field.getText());
            resultado_label.setText(String.format("%.1fºC convertidos para Fahrenheit são %.1fºF", celsius, ((9 * celsius + 160) / 5.0))); 
        } else if (check_celsius == 0 && check_fahrenheit != 0){
            Double fahrenheit = Double.parseDouble(fahrenheit_field.getText());
            resultado_label.setText(String.format("%.1fºF convertidos para Celsius são %.1fºC", fahrenheit, ((fahrenheit - 32) * (5.0/9.0)))); 
        } else if (check_celsius != 0 && check_fahrenheit != 0){
            resultado_label.setText("Por favor preencha somente um dos campos!"); 
        } else {
            resultado_label.setText("Por favor preencha um dos campos!"); 
        }
    }
}
