/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poofatec;

/**
 *
 * @author Aluno
 */
public class PesoIdeal_Swing extends javax.swing.JFrame {

    /**
     * Creates new form PesoIdeal_Swing
     */
    public PesoIdeal_Swing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tittle_label = new javax.swing.JLabel();
        clear_button = new javax.swing.JButton();
        sex_field = new javax.swing.JTextField();
        height_label = new javax.swing.JLabel();
        sex_label = new javax.swing.JLabel();
        height_field = new javax.swing.JTextField();
        result_label = new javax.swing.JLabel();
        calc_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tittle_label.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 24)); // NOI18N
        tittle_label.setText("Descubra seu peso ideal");

        clear_button.setText("Limpar");
        clear_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_buttonActionPerformed(evt);
            }
        });

        sex_field.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        sex_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sex_fieldActionPerformed(evt);
            }
        });

        height_label.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        height_label.setText("Digite a sua altura: ");

        sex_label.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        sex_label.setText("Selecione seu sexo 1 - Masculino ou 2 - Feminino:");

        height_field.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        height_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                height_fieldActionPerformed(evt);
            }
        });

        result_label.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N

        calc_button.setText("Calcular");
        calc_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tittle_label)
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sex_label)
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sex_field, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(238, 238, 238))))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(height_field, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(height_label)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(result_label, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(calc_button, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clear_button, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(tittle_label)
                .addGap(39, 39, 39)
                .addComponent(sex_label)
                .addGap(18, 18, 18)
                .addComponent(sex_field, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(height_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(height_field, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(calc_button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clear_button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(result_label, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clear_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_buttonActionPerformed
        clear();
    }//GEN-LAST:event_clear_buttonActionPerformed

    private void sex_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sex_fieldActionPerformed
        
    }//GEN-LAST:event_sex_fieldActionPerformed

    private void height_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_height_fieldActionPerformed
        
    }//GEN-LAST:event_height_fieldActionPerformed

    private void calc_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc_buttonActionPerformed
        calcular();
    }//GEN-LAST:event_calc_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesoIdeal_Swing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesoIdeal_Swing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesoIdeal_Swing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesoIdeal_Swing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesoIdeal_Swing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calc_button;
    private javax.swing.JButton clear_button;
    private javax.swing.JTextField height_field;
    private javax.swing.JLabel height_label;
    private javax.swing.JLabel result_label;
    private javax.swing.JTextField sex_field;
    private javax.swing.JLabel sex_label;
    private javax.swing.JLabel tittle_label;
    // End of variables declaration//GEN-END:variables

    private void calcular(){
        Float altura = Float.parseFloat(height_field.getText());
        Integer opcao = Integer.parseInt(sex_field.getText());
        
        if (opcao != 1 && opcao != 2)
            result_label.setText("Por favor, insira um sexo válido!");
        else if (opcao == 1)
           result_label.setText(String.format("Seu peso ideal é: %.2fkg", ((72.7*altura)-58)));
        else
           result_label.setText(String.format("Seu peso ideal é: %.2fkg", ((62.1*altura)-44.7))); 
    }
    
    private void clear(){
        result_label.setText("");
        sex_field.setText("");
        height_field.setText("");
        
        sex_field.requestFocus();
               
    }
}
